### ISSUE TITLE
What is the difference between KMamiz and Kiali which uses Jaeger?

### ISSUE THREAD

**Issue by EdisonFu** [stanley2058/KMamiz#5]

**Comment by stanley2058** [comment]
Thanks for the question,

KMamiz and Kiali are similar in some sense but otherwise quite different.

Kiali is helpful when managing an Istio cluster and provides excellent visualization of inter-service traffic. Kiali also includes functionalities to alter the Istio cluster configs, allowing easy traffic management.

On the other hand, KMamiz provides insights into the services running in the cluster. Once the KMamiz's Envoy filter is injected into Isito's sidecar, KMamiz can record and reconstruct endpoint-level request and response schemas, which allows automatic API documentation generation for the monitored services.

KMamiz also provides software quality metrics based on academic research:
- https://www.researchgate.net/publication/319955060_Automatically_Measuring_the_Maintainability_of_Service-and_Microservice-based_Systems_-_a_Literature_Review
- https://www.researchgate.net/publication/216843550_R_Product_metrics_for_service-oriented_infrastructures
- https://www.researchgate.net/publication/4292925_Cohesion_Metrics_for_Predicting_Maintainability_of_Service-Oriented_Software

Currently, KMamiz uses traces collected by Zipkin (similar to Jaeger but with fewer functionalities). I have some ideas on removing Zipkin and only relying on data collected by KMamiz's Envoy filter to reconstruct the service topology. Still, as for now, nothing is planned, so don't expect too much on that.

For more information, you can take a look at https://github.com/stanley2058/KMamiz/blob/main/docs/ARCHITECTURE.md or the published [conference paper](https://ieeexplore.ieee.org/document/10043222).
